FNSB.Publicworks.CapitalProjects.Tracking/UI/Models/ProjectManager.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FNSB.PW.Projects.Web.Models
{
    [Table("Publicworks.ProjectManagers")]
    public partial class ProjectManager
    {
        public ProjectManager()
        {
        }

        [Key]
        public int ppr_recordid { get; set; }

        [StringLength(50)]
        public string firstname { get; set; }

        [StringLength(50)]
        public string lastname { get; set; }

        public int? order { get; set; }
    }
}

FNSB.Publicworks.CapitalProjects.Tracking/UI/Controllers/ProjectManagersController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using FNSB.PW.Projects.Web.Models;

namespace FNSB.PW.Projects.Web.Controllers
{
    public class ProjectManagersController : Controller
    {
        private PubworksModel db = new PubworksModel();

        // GET: ProjectManagers
        public ActionResult Index()
        {
            return View(db.ProjectManagers.ToList());
        }

        //Active Managers Focuses on getting PM's of active projects up to the surface of the site
        public ActionResult ActiveManagers()
        {
            //select list of all project managers in the system
            var pma = db.ProjectManagers.Select(s => s.ppr_recordid).ToList();

            //fetch a list of all active projects and group them by project manager record ID
            var pa = db.Projects.Where(l => pma.Contains(l.ppr_recordid)).Where(f => f.PPM_Project_Active == true).GroupBy(d => d.ppr_recordid);

            var pml = new List<ProjectManager>();
            var pmp = new List<Project>();

            //dictionary of values for the manager ID and concat name
            Dictionary<int, string> manager = new Dictionary<int, string>();

            //loop the group project list and match the grouped ppr_recordid to the dictionary recordid. Add to the manager dictionary
            foreach (var pm in pa)
            {
                //match located
                if (pma.Contains(pm.Key))
                {
                    //get full ProjectManager record
                    var ds = db.ProjectManagers.FirstOrDefault(d => d.ppr_recordid == pm.Key);
                    if (ds != null)
                        //add to manager - ID is key and value is first+last name
                        manager.Add(ds.ppr_recordid, $"{ds.firstname} {ds.lastname}");
                        pml.Add(ds); //local List to populate the ManagerProjectViewModel

                    //foreach (var project in pm.ToList())
                    //    pmp.Add(project);
                }


            }
            //pass the dictionary to the viewbag
            ViewBag.Managers = manager;
            ViewBag.Projects = pmp;

            return View();
        } 


        // GET: ProjectManagers/Details/5
        public ActionResult Details(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProjectManager projectManager = db.ProjectManagers.Find(id);
            if (projectManager == null)
            {
                return HttpNotFound();
            }

            List<Project> projects = db.Projects.Where(p => p.ppr_recordid == id && p.PPM_Project_Active == true).ToList();

            var mpv = new ManagerProjectViewModel
            {
                ProjectProfileObject = new List<Project>(),
                ProjectManagerProfileObject = new ProjectManager()
            };

            mpv.ProjectManagerProfileObject.ppr_recordid = (int) id;
            mpv.ProjectManagerProfileObject.firstname = projectManager.firstname;
            mpv.ProjectManagerProfileObject.lastname = projectManager.lastname;


            foreach (var project in projects)
                mpv.ProjectProfileObject.Add(project);

            return View(mpv);
        }

        // GET: ProjectManagers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProjectManagers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ppr_recordid,firstname,lastname,order")] ProjectManager projectManager)
        {
            if (ModelState.IsValid)
            {
                db.ProjectManagers.Add(projectManager);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(projectManager);
        }

        // GET: ProjectManagers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProjectManager projectManager = db.ProjectManagers.Find(id);
            if (projectManager == null)
            {
                return HttpNotFound();
            }
            return View(projectManager);
        }

        // POST: ProjectManagers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ppr_recordid,firstname,lastname,order")] ProjectManager projectManager)
        {
            if (ModelState.IsValid)
            {
                db.Entry(projectManager).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(projectManager);
        }

        // GET: ProjectManagers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProjectManager projectManager = db.ProjectManagers.Find(id);
            if (projectManager == null)
            {
                return HttpNotFound();
            }
            return View(projectManager);
        }

        // POST: ProjectManagers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ProjectManager projectManager = db.ProjectManagers.Find(id);
            db.ProjectManagers.Remove(projectManager);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FNSB.Publicworks.CapitalProjects.Tracking/UI/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using FNSB.PW.Projects.Web.Models;

namespace FNSB.PW.Projects.Web.Controllers
{
    public class ProjectsController : Controller
    {
        private PubworksModel db = new PubworksModel();

        // GET: Projects
        public PartialViewResult ActiveProjectsData(string projectSearch, int? page, string selectedStatus = "Active")
        {

            Project.SelectStatus selected = (Project.SelectStatus)Enum.Parse(typeof(Project.SelectStatus), selectedStatus);
            IEnumerable<Project> data;

            switch (selected)
            {
                case Project.SelectStatus.Active:

                    data = projectSearch != null
                        ? db.Projects.Where(s => s.PPM_Project_Name.Contains(projectSearch) &&
                                                 s.PPM_Project_Active == true)
                            .OrderByDescending(p => p.PPM_Active_Date)
                        : db.Projects.Where(s => s.PPM_Project_Active == true)
                            .OrderByDescending(p => p.PPM_Active_Date);
                    break;

                case Project.SelectStatus.Inactive:
                    data = projectSearch != null
                        ? db.Projects.Where(s => s.PPM_Project_Name.Contains(projectSearch) &&
                                                 s.PPM_Project_Active == false)
                            .OrderByDescending(p => p.PPM_Active_Date)
                        : db.Projects.Where(s => s.PPM_Project_Active == false)
                            .OrderByDescending(p => p.PPM_Active_Date);
                    break;
                case Project.SelectStatus.All:
                    data = projectSearch != null
                        ? db.Projects.Where(s => s.PPM_Project_Name.Contains(projectSearch))
                            .OrderByDescending(p => p.PPM_Active_Date)
                        : db.Projects.OrderByDescending(p => p.PPM_Active_Date);
                    break;
                default:
                    data = db.Projects.OrderByDescending(p => p.PPM_Active_Date);
                    break;
            }

            return PartialView(data);
        }

        public ActionResult ActiveProjects()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Index(string prefix)
        {
            
            var name = db.Projects.Where(p => p.PPM_Project_Name.StartsWith(prefix));
            return Json(name, JsonRequestBehavior.AllowGet);
        }


        // GET: Projects/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // GET: Projects/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PPM_Recordid,PPM_Project_Name,PPM_Project_Number,PPM_Active_Date,PPM_Inactive_Date,PPM_Project_Active,PPM_Status_Desc,PPM_Per_Des_Complete,PPM_Proj_Scope,PPM_MSA_Update,PPM_Consultant_Fee,PPM_Contract_Amount,PPM_Contract_Amendments,PPM_CO,PPM_Per_Const_Complete,PPM_IFB_RFQ,PPM_User_Letter,PPM_RFP_Number,NDI_RFP,NDI_Scope,NDI_Advertise_for_Bid,NDI_Original_Bid_Date,NDI_Bid_Opening,NDI_Gen_Serv_Review,NDI_Consultant_Award,NDI_Construction_Bid_Award,NDI_Design_Complete,NDI_Agenda_Setting,NDI_Assembly_Approval,NDI_NTP,NDI_Substantial_Completion,NDI_Final,NDI_Warranty_Period_Ends,NDI_Closed,PPS_Recordid,PPU_Recordid,PPT_Recordid,PPR_Recordid,PPC_Recordid,PPA_Recordid,PPN_Recordid,NOU_Recordid,FFM_Recordid,ppm_project_complete")] Project project)
        {
            if (ModelState.IsValid)
            {
                db.Projects.Add(project);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(project);
        }

        // GET: Projects/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PPM_Recordid,PPM_Project_Name,PPM_Project_Number,PPM_Active_Date,PPM_Inactive_Date,PPM_Project_Active,PPM_Status_Desc,PPM_Per_Des_Complete,PPM_Proj_Scope,PPM_MSA_Update,PPM_Consultant_Fee,PPM_Contract_Amount,PPM_Contract_Amendments,PPM_CO,PPM_Per_Const_Complete,PPM_IFB_RFQ,PPM_User_Letter,PPM_RFP_Number,NDI_RFP,NDI_Scope,NDI_Advertise_for_Bid,NDI_Original_Bid_Date,NDI_Bid_Opening,NDI_Gen_Serv_Review,NDI_Consultant_Award,NDI_Construction_Bid_Award,NDI_Design_Complete,NDI_Agenda_Setting,NDI_Assembly_Approval,NDI_NTP,NDI_Substantial_Completion,NDI_Final,NDI_Warranty_Period_Ends,NDI_Closed,PPS_Recordid,PPU_Recordid,PPT_Recordid,PPR_Recordid,PPC_Recordid,PPA_Recordid,PPN_Recordid,NOU_Recordid,FFM_Recordid,ppm_project_complete")] Project project)
        {
            if (ModelState.IsValid)
            {
                db.Entry(project).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(project);
        }

        // GET: Projects/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Project project = db.Projects.Find(id);
            db.Projects.Remove(project);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FNSB.Publicworks.CapitalProjects.Tracking/UI/Views/ProjectManagers/ActiveManagers.cshtml
@model FNSB.PW.Projects.Web.Models.ProjectManager

@{
    ViewBag.Title = "ActiveManagers";
}

<h2>Project Managers</h2>

<div>
    
    <hr/>

    @using (Html.BeginForm())
    {
        <ul>
            @foreach (var i in ViewBag.Managers)
            {
                var ky = @i.Key;
                <li>
                    <a href="@Url.Action("Details", "ProjectManagers", new {id = ky})">@i.Value</a>
                </li>
            }
        </ul>
    }


    <dl class="dl-horizontal">

        @*<dt>
            @Html.DisplayNameFor(model => model.)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.firstname)
        </dd>*@

        @*<dt>
            @Html.DisplayNameFor(model => model.lastname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.order)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.order)
        </dd>*@

    </dl>
</div>
<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.ppr_recordid }) |
    @Html.ActionLink("Back to List", "Index")*@
</p>

FNSB.Publicworks.CapitalProjects.Tracking/UI/Views/ProjectManagers/Create.cshtml
@model FNSB.PW.Projects.Web.Models.ProjectManager

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProjectManager</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.firstname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.firstname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.firstname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lastname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lastname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lastname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.order, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.order, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.order, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FNSB.Publicworks.CapitalProjects.Tracking/UI/Views/ProjectManagers/Delete.cshtml
@model FNSB.PW.Projects.Web.Models.ProjectManager

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProjectManager</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.firstname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.firstname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lastname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.order)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.order)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FNSB.Publicworks.CapitalProjects.Tracking/UI/Views/ProjectManagers/Details.cshtml
@using System.Web.Mvc.Html
@model FNSB.PW.Projects.Web.Models.ManagerProjectViewModel
@{
    ViewBag.Title = "Details";
}

<div>
    <h2>@string.Format("{0} {1}", @Model.ProjectManagerProfileObject.firstname, @Model.ProjectManagerProfileObject.lastname)</h2>
<div>

<table class="table">
<tr>
    <th>
        Project Name
    </th>
    <th>
        Project
    </th>
    <th>
        Active Date
    </th>
    <th></th>
</tr>

@foreach (var item in Model.ProjectProfileObject.ToList())
{ 
    <tr>
        <td>
            @Html.ActionLink(item.PPM_Project_Name, "Details", "Projects", new {id = item.PPM_Recordid}, null)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PPM_Project_Number)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PPM_Active_Date)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new {id = item.PPM_Recordid}) |
            @Html.ActionLink("Details", "Details", new {id = item.PPM_Recordid}) |
            @Html.ActionLink("Delete", "Delete", new {id = item.PPM_Recordid})
        </td>
    </tr>
}

</table>
</div>
    
    
    

</div>
<p>
   @* @Html.ActionLink("Edit", "Edit", new { id = @model.ppr_recordid }) |*@
    @Html.ActionLink("Back to List", "Index")
</p>

FNSB.Publicworks.CapitalProjects.Tracking/UI/Views/ProjectManagers/Edit.cshtml
@model FNSB.PW.Projects.Web.Models.ProjectManager

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProjectManager</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ppr_recordid)

        <div class="form-group">
            @Html.LabelFor(model => model.firstname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.firstname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.firstname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lastname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lastname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lastname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.order, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.order, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.order, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FNSB.Publicworks.CapitalProjects.Tracking/UI/Views/ProjectManagers/Index.cshtml
@model List<FNSB.PW.Projects.Web.Models.ProjectManager>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.firstname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.lastname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.order)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.firstname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.lastname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.order)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ppr_recordid }) |
            @Html.ActionLink("Details", "Details", new { id=item.ppr_recordid }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ppr_recordid })
        </td>
    </tr>
}

</table>